  [1m[35m (0.6ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (405.4ms)[0m  [1m[35mCREATE TABLE `schema_migrations` (`version` varchar(255) NOT NULL PRIMARY KEY) ENGINE=InnoDB[0m
  [1m[35m (231.2ms)[0m  [1m[35mCREATE TABLE `ar_internal_metadata` (`key` varchar(255) NOT NULL PRIMARY KEY, `value` varchar(255), `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT GET_LOCK('148854866579402445', 0)[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
Migrating to CreateUsers (20200128063302)
  [1m[35m (231.0ms)[0m  [1m[35mCREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255), `email` varchar(255), `password_digest` varchar(255), `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB[0m
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (1.3ms)[0m  [1m[32mINSERT INTO `schema_migrations` (`version`) VALUES ('20200128063302')[0m
  [1m[35m (35.3ms)[0m  [1m[35mCOMMIT[0m
  [1m[36mActiveRecord::InternalMetadata Load (0.9ms)[0m  [1m[34mSELECT  `ar_internal_metadata`.* FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'environment' LIMIT 1[0m
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (0.9ms)[0m  [1m[32mINSERT INTO `ar_internal_metadata` (`key`, `value`, `created_at`, `updated_at`) VALUES ('environment', 'development', '2020-01-28 06:34:13', '2020-01-28 06:34:13')[0m
  [1m[35m (40.6ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.6ms)[0m  [1m[34mSELECT RELEASE_LOCK('148854866579402445')[0m
  [1m[35m (0.8ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
  [1m[35m (0.4ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (0.6ms)[0m  [1m[32mINSERT INTO `users` (`email`, `password_digest`, `created_at`, `updated_at`) VALUES ('example@mail.com', '$2a$12$M0nJoqcygkxbPc7QQlBVTu/tqNQxMADvJ0a9rnnfw4cX8/xOzEyJW', '2020-01-28 06:48:25', '2020-01-28 06:48:25')[0m
  [1m[35m (37.0ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.4ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.3ms)[0m  [1m[34mSELECT GET_LOCK('148854866579402445', 0)[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
Migrating to CreateItems (20200128064902)
  [1m[35m (457.1ms)[0m  [1m[35mCREATE TABLE `items` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255), `description` text, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB[0m
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (1.2ms)[0m  [1m[32mINSERT INTO `schema_migrations` (`version`) VALUES ('20200128064902')[0m
  [1m[35m (115.1ms)[0m  [1m[35mCOMMIT[0m
  [1m[36mActiveRecord::InternalMetadata Load (0.9ms)[0m  [1m[34mSELECT  `ar_internal_metadata`.* FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'environment' LIMIT 1[0m
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.4ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.6ms)[0m  [1m[34mSELECT RELEASE_LOCK('148854866579402445')[0m
  [1m[35m (0.8ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
Started GET "/" for ::1 at 2020-01-28 12:20:03 +0530
  [1m[35m (0.5ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
Processing by Rails::WelcomeController#index as HTML
  Rendering C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/templates/rails/welcome/index.html.erb
  Rendered C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/templates/rails/welcome/index.html.erb (10.1ms)
Completed 200 OK in 82ms (Views: 55.7ms | ActiveRecord: 0.0ms)


Started GET "/authenticate" for ::1 at 2020-01-28 12:20:25 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for ::1 at 2020-01-28 12:21:06 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for 127.0.0.1 at 2020-01-28 12:22:14 +0530
  [1m[35m (0.7ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.6ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/items" for 127.0.0.1 at 2020-01-28 12:23:05 +0530
Processing by ItemsController#index as HTML
Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started GET "/items" for 127.0.0.1 at 2020-01-28 12:24:17 +0530
Processing by ItemsController#index as HTML
Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started GET "/authenticate" for 127.0.0.1 at 2020-01-28 12:26:05 +0530
  [1m[35m (0.6ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for ::1 at 2020-01-28 12:28:02 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/items" for ::1 at 2020-01-28 12:31:55 +0530
  [1m[35m (0.4ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
Processing by ItemsController#index as HTML
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started GET "/items" for ::1 at 2020-01-28 12:43:13 +0530
  [1m[35m (0.5ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
Processing by ItemsController#index as */*
  Parameters: {"item"=>{}}
Completed 500 Internal Server Error in 2ms (ActiveRecord: 69.6ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started GET "/authenticate" for ::1 at 2020-01-28 12:43:48 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for ::1 at 2020-01-28 12:43:52 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started POST "/authe" for ::1 at 2020-01-28 12:46:53 +0530
  
ActionController::RoutingError (No route matches [POST] "/authe"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started POST "/authenticate" for ::1 at 2020-01-28 12:48:44 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
Completed 500 Internal Server Error in 413ms (ActiveRecord: 30.0ms)


  
NameError (uninitialized constant AuthenticateUser::JsonWebToken):
  
app/commands/authenticate_user.rb:10:in `call'
app/controllers/authentication_controller.rb:5:in `authenticate'
Started POST "/authenticate" for ::1 at 2020-01-28 12:49:09 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
Completed 500 Internal Server Error in 294ms (ActiveRecord: 0.5ms)


  
NameError (uninitialized constant AuthenticateUser::JsonWebToken):
  
app/commands/authenticate_user.rb:10:in `call'
app/controllers/authentication_controller.rb:5:in `authenticate'
Started POST "/authenticate" for ::1 at 2020-01-28 12:52:37 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
Completed 500 Internal Server Error in 369ms (ActiveRecord: 64.3ms)


  
NameError (uninitialized constant AuthenticateUser::JsonWebToken):
  
app/commands/authenticate_user.rb:10:in `call'
app/controllers/authentication_controller.rb:5:in `authenticate'
Started GET "/items" for ::1 at 2020-01-28 12:53:48 +0530
Processing by ItemsController#index as */*
  Parameters: {"item"=>{}}
Completed 500 Internal Server Error in 16ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started POST "/authenticate" for ::1 at 2020-01-28 13:28:34 +0530
  [1m[35m (0.5ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
Processing by AuthenticationController#authenticate as */*
  Parameters: {"{\n\"email\":\"example@mail.com\",\n\"password\":\"123123123\"\n}"=>"[FILTERED]"}
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` IS NULL LIMIT 1[0m
Completed 401 Unauthorized in 75ms (Views: 0.3ms | ActiveRecord: 53.7ms)


Started POST "/authenticate" for ::1 at 2020-01-28 13:33:32 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"{\n\"email\":\"example@mail.com\",\n\"password\":\"123123123\"\n}"=>"[FILTERED]"}
  [1m[35m (0.4ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` IS NULL LIMIT 1[0m
Completed 401 Unauthorized in 5ms (Views: 0.3ms | ActiveRecord: 0.9ms)


Started POST "/authenticate" for ::1 at 2020-01-28 13:36:31 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
Completed 500 Internal Server Error in 372ms (ActiveRecord: 1.9ms)


  
NameError (uninitialized constant AuthenticateUser::JsonWebToken):
  
app/commands/authenticate_user.rb:10:in `call'
app/controllers/authentication_controller.rb:5:in `authenticate'
Started GET "/items" for ::1 at 2020-01-28 13:37:12 +0530
Processing by ItemsController#index as HTML
Completed 500 Internal Server Error in 8ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started POST "/authenticate" for ::1 at 2020-01-28 13:37:39 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"{\n\"email\":\"example@mail.com\",\n\"password\":\"123123123\"\n}"=>"[FILTERED]"}
  [1m[36mUser Load (0.8ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` IS NULL LIMIT 1[0m
Completed 401 Unauthorized in 3ms (Views: 0.3ms | ActiveRecord: 0.8ms)


Started POST "/authenticate" for ::1 at 2020-01-28 13:38:37 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
Completed 500 Internal Server Error in 290ms (ActiveRecord: 0.6ms)


  
NameError (uninitialized constant AuthenticateUser::JsonWebToken):
  
app/commands/authenticate_user.rb:10:in `call'
app/controllers/authentication_controller.rb:5:in `authenticate'
Started POST "/authenticate" for ::1 at 2020-01-28 13:39:10 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (1.5ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
Completed 500 Internal Server Error in 298ms (ActiveRecord: 1.5ms)


  
NameError (uninitialized constant AuthenticateUser::JsonWebToken):
  
app/commands/authenticate_user.rb:10:in `call'
app/controllers/authentication_controller.rb:5:in `authenticate'
Started POST "/authenticate" for ::1 at 2020-01-28 13:40:51 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"{\n\"email\":\"example@mail.com\",\n\"password\":\"123123123\"\n}"=>"[FILTERED]"}
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` IS NULL LIMIT 1[0m
Completed 401 Unauthorized in 2ms (Views: 0.3ms | ActiveRecord: 0.6ms)


  [1m[35m (1.0ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.9ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (45.4ms)[0m  [1m[32mINSERT INTO `users` (`email`, `password_digest`, `created_at`, `updated_at`) VALUES ('example@mail.com', '$2a$12$1CcMXPTqWGw/2F231oWYVexgNxKcof5O4DO7sXRk4SJ2jqoNDTI96', '2020-01-28 09:55:57', '2020-01-28 09:55:57')[0m
  [1m[35m (39.7ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.6ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (7.8ms)[0m  [1m[32mINSERT INTO `items` (`name`, `description`, `created_at`, `updated_at`) VALUES ('bhavani', 'hiiiiii', '2020-01-28 09:55:57', '2020-01-28 09:55:57')[0m
  [1m[35m (36.6ms)[0m  [1m[35mCOMMIT[0m
Started GET "/" for ::1 at 2020-01-28 15:29:43 +0530
  [1m[35m (0.4ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
Processing by Rails::WelcomeController#index as HTML
  Rendering C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/templates/rails/welcome/index.html.erb
  Rendered C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/templates/rails/welcome/index.html.erb (32.0ms)
Completed 200 OK in 228ms (Views: 124.4ms | ActiveRecord: 0.0ms)


Started GET "/authenticate" for ::1 at 2020-01-28 15:29:53 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for ::1 at 2020-01-28 15:31:13 +0530
  [1m[35m (0.4ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/items" for ::1 at 2020-01-28 15:31:43 +0530
Processing by ItemsController#index as HTML
Completed 500 Internal Server Error in 13ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started GET "/authenticate" for ::1 at 2020-01-28 15:42:19 +0530
  
Mysql2::Error::ConnectionError (Can't connect to MySQL server on 'localhost' (10061)):
  
mysql2-0.5.3-x64 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.3-x64 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.1.7) lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `new'
activerecord (5.1.7) lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `mysql2_connection'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:761:in `new_connection'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:805:in `checkout_new_connection'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:784:in `try_to_checkout_new_connection'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:745:in `acquire_connection'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:502:in `checkout'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:376:in `connection'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:933:in `retrieve_connection'
activerecord (5.1.7) lib/active_record/connection_handling.rb:116:in `retrieve_connection'
activerecord (5.1.7) lib/active_record/connection_handling.rb:88:in `connection'
activerecord (5.1.7) lib/active_record/migration.rb:562:in `connection'
activerecord (5.1.7) lib/active_record/migration.rb:553:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.7) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2020-01-28 15:42:26 +0530
  
Mysql2::Error::ConnectionError (Can't connect to MySQL server on 'localhost' (10061)):
  
mysql2-0.5.3-x64 (mingw32) lib/mysql2/client.rb:90:in `connect'
mysql2-0.5.3-x64 (mingw32) lib/mysql2/client.rb:90:in `initialize'
activerecord (5.1.7) lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `new'
activerecord (5.1.7) lib/active_record/connection_adapters/mysql2_adapter.rb:21:in `mysql2_connection'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:761:in `new_connection'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:805:in `checkout_new_connection'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:784:in `try_to_checkout_new_connection'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:745:in `acquire_connection'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:502:in `checkout'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:376:in `connection'
activerecord (5.1.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:933:in `retrieve_connection'
activerecord (5.1.7) lib/active_record/connection_handling.rb:116:in `retrieve_connection'
activerecord (5.1.7) lib/active_record/connection_handling.rb:88:in `connection'
activerecord (5.1.7) lib/active_record/migration.rb:562:in `connection'
activerecord (5.1.7) lib/active_record/migration.rb:553:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.7) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for ::1 at 2020-01-28 15:42:55 +0530
  [1m[35m (0.7ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2020-01-28 15:42:56 +0530
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/" for ::1 at 2020-01-28 16:59:42 +0530
  [1m[35m (0.4ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
Processing by Rails::WelcomeController#index as HTML
  Rendering C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/templates/rails/welcome/index.html.erb
  Rendered C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/templates/rails/welcome/index.html.erb (5.9ms)
Completed 200 OK in 55ms (Views: 17.0ms | ActiveRecord: 0.0ms)


Started GET "/authenticate" for ::1 at 2020-01-28 16:59:53 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/items" for ::1 at 2020-01-28 17:00:02 +0530
Processing by ItemsController#index as HTML
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started GET "/" for ::1 at 2020-01-28 17:07:41 +0530
  [1m[35m (0.5ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
Processing by Rails::WelcomeController#index as HTML
  Rendering C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/templates/rails/welcome/index.html.erb
  Rendered C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/templates/rails/welcome/index.html.erb (4.5ms)
Completed 200 OK in 19ms (Views: 16.0ms | ActiveRecord: 0.0ms)


Started GET "/favicon.ico" for ::1 at 2020-01-28 17:07:41 +0530
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for ::1 at 2020-01-28 17:07:54 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/items" for ::1 at 2020-01-28 17:08:50 +0530
Processing by ItemsController#index as HTML
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started GET "/authentication" for ::1 at 2020-01-28 17:10:22 +0530
  
ActionController::RoutingError (No route matches [GET] "/authentication"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/items" for ::1 at 2020-01-28 17:10:42 +0530
Processing by ItemsController#index as HTML
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started GET "/items" for ::1 at 2020-01-28 20:26:55 +0530
  [1m[35m (0.8ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.9ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
Processing by ItemsController#index as HTML
Completed 500 Internal Server Error in 7ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started GET "/favicon.ico" for ::1 at 2020-01-28 20:26:58 +0530
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/items" for ::1 at 2020-01-28 20:31:21 +0530
Processing by ItemsController#index as HTML
Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started GET "/items" for ::1 at 2020-01-28 20:31:22 +0530
Processing by ItemsController#index as HTML
Completed 500 Internal Server Error in 6ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started GET "/items" for ::1 at 2020-01-28 20:31:23 +0530
Processing by ItemsController#index as HTML
Completed 500 Internal Server Error in 8ms (ActiveRecord: 0.0ms)


  
NameError (uninitialized constant AuthorizeApiRequest::JsonWebToken):
  
app/commands/authorize_api_request.rb:22:in `decoded_auth_token'
app/commands/authorize_api_request.rb:17:in `user'
app/commands/authorize_api_request.rb:9:in `call'
app/controllers/application_controller.rb:8:in `authenticate_request'
Started GET "/items" for ::1 at 2020-01-28 20:39:53 +0530
  [1m[35m (0.4ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
Processing by ItemsController#index as HTML
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 5ms (Views: 0.3ms | ActiveRecord: 0.0ms)


Started GET "/authenticate" for ::1 at 2020-01-28 20:41:31 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/items" for ::1 at 2020-01-28 20:41:45 +0530
Processing by ItemsController#index as HTML
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 0ms (Views: 0.1ms | ActiveRecord: 0.0ms)


Started GET "/items" for ::1 at 2020-01-28 20:42:40 +0530
Processing by ItemsController#index as HTML
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.3ms | ActiveRecord: 0.0ms)


Started GET "/items" for ::1 at 2020-01-28 20:42:41 +0530
Processing by ItemsController#index as HTML
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.4ms | ActiveRecord: 0.0ms)


Started GET "/items" for ::1 at 2020-01-28 20:45:09 +0530
Processing by ItemsController#index as HTML
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.3ms | ActiveRecord: 0.0ms)


Started GET "/items" for ::1 at 2020-01-28 21:10:56 +0530
Processing by ItemsController#index as HTML
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.4ms | ActiveRecord: 0.0ms)


Started GET "/authenticate" for ::1 at 2020-01-28 21:11:11 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for ::1 at 2020-01-28 21:13:09 +0530
  [1m[35m (0.5ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/items" for ::1 at 2020-01-28 21:13:22 +0530
Processing by ItemsController#index as HTML
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 6ms (Views: 0.8ms | ActiveRecord: 0.0ms)


Started GET "/items" for ::1 at 2020-01-28 21:13:58 +0530
Processing by ItemsController#index as */*
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.2ms | ActiveRecord: 0.0ms)


Started POST "/authenticate" for ::1 at 2020-01-28 21:14:26 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[35m (0.3ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[36mUser Load (15.8ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m  [["email", "example@mail.com"], ["LIMIT", 1]]
Completed 200 OK in 2055ms (Views: 0.4ms | ActiveRecord: 155.7ms)


Started GET "/items" for ::1 at 2020-01-28 21:14:45 +0530
Processing by ItemsController#index as */*
  Parameters: {"item"=>{}}
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 0ms (Views: 0.2ms | ActiveRecord: 24.1ms)


Started GET "/authenticate" for ::1 at 2020-01-28 21:15:03 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started POST "/authenticate" for ::1 at 2020-01-28 21:15:11 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (1.5ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m  [["email", "example@mail.com"], ["LIMIT", 1]]
Completed 200 OK in 1626ms (Views: 0.3ms | ActiveRecord: 1.5ms)


Started GET "/authenticate" for ::1 at 2020-01-28 21:17:09 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for ::1 at 2020-01-28 21:17:11 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for ::1 at 2020-01-28 21:17:11 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for ::1 at 2020-01-28 21:17:11 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for ::1 at 2020-01-28 21:17:12 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for ::1 at 2020-01-28 23:13:50 +0530
  [1m[35m (18.2ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/authenticate" for ::1 at 2020-01-28 23:15:13 +0530
  
ActionController::RoutingError (No route matches [GET] "/authenticate"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/items" for ::1 at 2020-01-28 23:15:45 +0530
Processing by ItemsController#index as HTML
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 5ms (Views: 0.2ms | ActiveRecord: 0.0ms)


Started GET "/items" for ::1 at 2020-01-28 23:16:24 +0530
Processing by ItemsController#index as */*
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.3ms | ActiveRecord: 0.0ms)


Started POST "/authenticate" for ::1 at 2020-01-28 23:17:38 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (1.2ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m  [["email", "example@mail.com"], ["LIMIT", 1]]
Completed 200 OK in 995ms (Views: 0.5ms | ActiveRecord: 135.9ms)


Started GET "/items" for ::1 at 2020-01-28 23:18:53 +0530
Processing by ItemsController#index as */*
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.2ms | ActiveRecord: 0.0ms)


Started GET "/items" for ::1 at 2020-01-28 23:31:21 +0530
Processing by ItemsController#index as */*
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.4ms | ActiveRecord: 0.0ms)


Started GET "/items" for ::1 at 2020-01-28 23:31:48 +0530
Processing by ItemsController#index as */*
  Parameters: {"item"=>{}}
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.3ms | ActiveRecord: 125.5ms)


  [1m[35m (0.8ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (300.6ms)[0m  [1m[35mCREATE TABLE `schema_migrations` (`version` varchar(255) NOT NULL PRIMARY KEY) ENGINE=InnoDB[0m
  [1m[35m (328.0ms)[0m  [1m[35mCREATE TABLE `ar_internal_metadata` (`key` varchar(255) NOT NULL PRIMARY KEY, `value` varchar(255), `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT GET_LOCK('148854866579402445', 0)[0m
  [1m[35m (0.9ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
Migrating to CreateUsers (20200128063302)
  [1m[35m (197.8ms)[0m  [1m[35mCREATE TABLE `users` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255), `email` varchar(255), `password_digest` varchar(255), `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB[0m
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (30.7ms)[0m  [1m[32mINSERT INTO `schema_migrations` (`version`) VALUES ('20200128063302')[0m
  [1m[35m (27.3ms)[0m  [1m[35mCOMMIT[0m
Migrating to CreateItems (20200128064902)
  [1m[35m (192.0ms)[0m  [1m[35mCREATE TABLE `items` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255), `description` text, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL) ENGINE=InnoDB[0m
  [1m[35m (0.4ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (1.1ms)[0m  [1m[32mINSERT INTO `schema_migrations` (`version`) VALUES ('20200128064902')[0m
  [1m[35m (61.7ms)[0m  [1m[35mCOMMIT[0m
  [1m[36mActiveRecord::InternalMetadata Load (0.9ms)[0m  [1m[34mSELECT  `ar_internal_metadata`.* FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'environment' LIMIT 1[0m
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (1.3ms)[0m  [1m[32mINSERT INTO `ar_internal_metadata` (`key`, `value`, `created_at`, `updated_at`) VALUES ('environment', 'development', '2020-01-29 05:56:25', '2020-01-29 05:56:25')[0m
  [1m[35m (44.3ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT RELEASE_LOCK('148854866579402445')[0m
  [1m[35m (0.7ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
  [1m[35m (0.4ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.8ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (63.5ms)[0m  [1m[32mINSERT INTO `users` (`email`, `password_digest`, `created_at`, `updated_at`) VALUES ('example@mail.com', '$2a$12$5eUNIXOPQbLutv.fB0/cle3ZH/ZRgk1YCpUVALG/waAvEpkCIo9VC', '2020-01-29 05:56:56', '2020-01-29 05:56:56')[0m
  [1m[35m (118.5ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (1.2ms)[0m  [1m[32mINSERT INTO `items` (`name`, `description`, `created_at`, `updated_at`) VALUES ('bhavani', 'hiiiiii', '2020-01-29 05:56:57', '2020-01-29 05:56:57')[0m
  [1m[35m (43.5ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.4ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.7ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (45.9ms)[0m  [1m[32mINSERT INTO `users` (`email`, `password_digest`, `created_at`, `updated_at`) VALUES ('example@mail.com', '$2a$12$U5RkC1GlcbDNpVQK8ScGl.h5fU9rEj0HXiTFmdui4nlNxOtvH1njK', '2020-01-29 06:09:21', '2020-01-29 06:09:21')[0m
  [1m[35m (59.9ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.3ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (1.0ms)[0m  [1m[32mINSERT INTO `items` (`name`, `description`, `created_at`, `updated_at`) VALUES ('bhavani', 'hiiiiii', '2020-01-29 06:09:21', '2020-01-29 06:09:21')[0m
  [1m[35m (55.2ms)[0m  [1m[35mCOMMIT[0m
Started GET "/items" for ::1 at 2020-01-29 12:20:42 +0530
  [1m[35m (0.8ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.6ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
Processing by ItemsController#index as */*
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 19ms (Views: 0.3ms | ActiveRecord: 0.0ms)


Started POST "/authenticate" for ::1 at 2020-01-29 12:25:26 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[35m (0.5ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[36mUser Load (1.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
Completed 401 Unauthorized in 569ms (Views: 0.2ms | ActiveRecord: 41.1ms)


Started POST "/authenticate" for ::1 at 2020-01-29 12:25:55 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m  [["email", "example@mail.com"], ["LIMIT", 1]]
Completed 200 OK in 696ms (Views: 0.1ms | ActiveRecord: 0.5ms)


Started GET "/items" for ::1 at 2020-01-29 12:29:22 +0530
Processing by ItemsController#index as */*
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1[0m
  [1m[36mItem Load (1.9ms)[0m  [1m[34mSELECT `items`.* FROM `items`[0m
Completed 200 OK in 106ms (Views: 19.8ms | ActiveRecord: 79.2ms)


Started POST "/authenticate" for ::1 at 2020-01-29 12:34:36 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m  [["email", "example@mail.com"], ["LIMIT", 1]]
Completed 200 OK in 857ms (Views: 0.2ms | ActiveRecord: 0.6ms)


Started POST "/authenticate" for ::1 at 2020-01-29 12:34:45 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m  [["email", "example@mail.com"], ["LIMIT", 1]]
Completed 200 OK in 1286ms (Views: 0.3ms | ActiveRecord: 0.6ms)


Started POST "/authenticate" for ::1 at 2020-01-29 12:34:54 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (1.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m  [["email", "example@mail.com"], ["LIMIT", 1]]
Completed 200 OK in 1112ms (Views: 0.3ms | ActiveRecord: 1.1ms)


Started GET "/items" for ::1 at 2020-01-29 12:36:32 +0530
Processing by ItemsController#index as */*
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.2ms | ActiveRecord: 0.0ms)


Started GET "/items" for ::1 at 2020-01-29 12:36:44 +0530
Processing by ItemsController#index as */*
  [1m[36mUser Load (1.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1[0m
  [1m[36mItem Load (0.6ms)[0m  [1m[34mSELECT `items`.* FROM `items`[0m
Completed 200 OK in 6ms (Views: 2.3ms | ActiveRecord: 1.5ms)


Started POST "/items" for ::1 at 2020-01-29 17:59:48 +0530
Processing by ItemsController#create as */*
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 3ms (Views: 1.5ms | ActiveRecord: 0.0ms)


Started POST "/items" for ::1 at 2020-01-29 18:00:07 +0530
Processing by ItemsController#create as */*
  [1m[36mUser Load (1.6ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1[0m
Completed 400 Bad Request in 13ms (ActiveRecord: 1.6ms)


  
ActionController::ParameterMissing (param is missing or the value is empty: item):
  
app/controllers/items_controller.rb:49:in `item_params'
app/controllers/items_controller.rb:18:in `create'
Started GET "/items" for ::1 at 2020-01-29 18:00:17 +0530
Processing by ItemsController#index as */*
  [1m[36mUser Load (1.3ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1[0m
  [1m[36mItem Load (1.8ms)[0m  [1m[34mSELECT `items`.* FROM `items`[0m
Completed 200 OK in 14ms (Views: 6.2ms | ActiveRecord: 3.1ms)


Started GET "/items" for ::1 at 2020-01-29 18:00:32 +0530
Processing by ItemsController#index as */*
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 1ms (Views: 0.5ms | ActiveRecord: 0.0ms)


Started GET "/" for ::1 at 2020-02-12 11:38:42 +0530
  [1m[35m (0.4ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[35m (0.7ms)[0m  [1m[34mSELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC[0m
  
TypeError (wrong argument type Class (expected Module)):
  
app/helpers/application_helper.rb:2:in `include'
app/helpers/application_helper.rb:2:in `<module:ApplicationHelper>'
app/helpers/application_helper.rb:1:in `<top (required)>'
Started POST "/authenticate" for ::1 at 2020-02-12 11:39:09 +0530
Processing by AuthenticationController#authenticate as */*
  [1m[35m (0.9ms)[0m  [1m[35mSET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483[0m
  [1m[36mUser Load (9.3ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` IS NULL LIMIT 1[0m
Completed 401 Unauthorized in 138ms (Views: 0.3ms | ActiveRecord: 81.2ms)


Started POST "/authenticate" for ::1 at 2020-02-12 11:39:44 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"authentication"=>{}}
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` IS NULL LIMIT 1[0m
Completed 401 Unauthorized in 2ms (Views: 0.2ms | ActiveRecord: 0.4ms)


Started POST "/authenticate" for ::1 at 2020-02-12 11:41:14 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (1.3ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
Completed 401 Unauthorized in 516ms (Views: 0.2ms | ActiveRecord: 3.5ms)


Started POST "/authenticate" for ::1 at 2020-02-12 11:42:17 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m  [["email", "example@mail.com"], ["LIMIT", 1]]
Completed 200 OK in 637ms (Views: 0.2ms | ActiveRecord: 0.6ms)


Started GET "/items" for ::1 at 2020-02-12 11:43:20 +0530
Processing by ItemsController#index as */*
  [1m[36mUser Load (11.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1[0m
  [1m[36mItem Load (14.2ms)[0m  [1m[34mSELECT `items`.* FROM `items`[0m
Completed 200 OK in 129ms (Views: 9.0ms | ActiveRecord: 55.0ms)


Started POST "/items" for ::1 at 2020-02-12 11:45:11 +0530
Error occurred while parsing request parameters.
Contents:

{
 "name": "rajesh",
  "description": "hellooo",


}
  
ActionDispatch::Http::Parameters::ParseError (767: unexpected token at '{
 "name": "rajesh",
  "description": "hellooo",


}'):
  
actionpack (5.1.7) lib/action_dispatch/http/parameters.rb:115:in `rescue in parse_formatted_parameters'
actionpack (5.1.7) lib/action_dispatch/http/parameters.rb:109:in `parse_formatted_parameters'
actionpack (5.1.7) lib/action_dispatch/http/request.rb:361:in `block in POST'
rack (2.1.2) lib/rack/request.rb:74:in `fetch'
rack (2.1.2) lib/rack/request.rb:74:in `fetch_header'
actionpack (5.1.7) lib/action_dispatch/http/request.rb:360:in `POST'
actionpack (5.1.7) lib/action_controller/metal/params_wrapper.rb:286:in `_wrapper_enabled?'
actionpack (5.1.7) lib/action_controller/metal/params_wrapper.rb:235:in `process_action'
activerecord (5.1.7) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.7) lib/abstract_controller/base.rb:124:in `process'
actionpack (5.1.7) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.7) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.7) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.7) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.7) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.7) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.7) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.7) lib/action_dispatch/routing/route_set.rb:844:in `call'
rack (2.1.2) lib/rack/etag.rb:27:in `call'
rack (2.1.2) lib/rack/conditional_get.rb:40:in `call'
rack (2.1.2) lib/rack/head.rb:14:in `call'
activerecord (5.1.7) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.7) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.7) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started POST "/items" for ::1 at 2020-02-12 11:45:21 +0530
Processing by ItemsController#create as */*
  Parameters: {"name"=>"rajesh", "description"=>"hellooo", "item"=>{"name"=>"rajesh", "description"=>"hellooo"}}
  [1m[36mUser Load (1.4ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1[0m
  [1m[35m (0.6ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (96.3ms)[0m  [1m[32mINSERT INTO `items` (`name`, `description`, `created_at`, `updated_at`) VALUES ('rajesh', 'hellooo', '2020-02-12 06:15:21', '2020-02-12 06:15:21')[0m
  [1m[35m (130.2ms)[0m  [1m[35mCOMMIT[0m
Completed 201 Created in 235ms (Views: 1.2ms | ActiveRecord: 228.4ms)


Started GET "/items" for ::1 at 2020-02-12 11:48:26 +0530
Processing by ItemsController#index as */*
  Parameters: {"item"=>{}}
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1[0m
  [1m[36mItem Load (0.4ms)[0m  [1m[34mSELECT `items`.* FROM `items`[0m
Completed 200 OK in 4ms (Views: 2.0ms | ActiveRecord: 0.9ms)


Started POST "/authenticate" for ::1 at 2020-02-12 12:47:10 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (1.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m  [["email", "example@mail.com"], ["LIMIT", 1]]
Completed 200 OK in 852ms (Views: 1.6ms | ActiveRecord: 1.0ms)


Started POST "/authenticate" for ::1 at 2020-02-12 12:47:58 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (2.1ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m  [["email", "example@mail.com"], ["LIMIT", 1]]
Completed 200 OK in 611ms (Views: 0.2ms | ActiveRecord: 2.1ms)


Started POST "/authenticate" for ::1 at 2020-02-12 12:48:24 +0530
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`email` = 'example@mail.com' LIMIT 1[0m  [["email", "example@mail.com"], ["LIMIT", 1]]
Completed 200 OK in 833ms (Views: 0.1ms | ActiveRecord: 0.5ms)


Started POST "/items" for ::1 at 2020-02-12 12:49:08 +0530
Processing by ItemsController#create as */*
  Parameters: {"name"=>"rajesh", "description"=>"hellooo", "item"=>{"name"=>"rajesh", "description"=>"hellooo"}}
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1[0m
  [1m[35m (0.2ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (45.2ms)[0m  [1m[32mINSERT INTO `items` (`name`, `description`, `created_at`, `updated_at`) VALUES ('rajesh', 'hellooo', '2020-02-12 07:19:08', '2020-02-12 07:19:08')[0m
  [1m[35m (95.6ms)[0m  [1m[35mCOMMIT[0m
Completed 201 Created in 157ms (Views: 5.4ms | ActiveRecord: 141.4ms)


Started GET "/items" for ::1 at 2020-02-12 12:49:25 +0530
Processing by ItemsController#index as */*
  Parameters: {"item"=>{}}
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1[0m
  [1m[36mItem Load (0.6ms)[0m  [1m[34mSELECT `items`.* FROM `items`[0m
Completed 200 OK in 6ms (Views: 3.0ms | ActiveRecord: 1.1ms)


Started GET "/items" for ::1 at 2020-02-12 17:58:24 +0530
Processing by ItemsController#index as HTML
Filter chain halted as :authenticate_request rendered or redirected
Completed 401 Unauthorized in 4ms (Views: 1.7ms | ActiveRecord: 0.0ms)


Started GET "/favicon.ico" for ::1 at 2020-02-12 17:58:24 +0530
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.7) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.7) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.1.2) lib/rack/runtime.rb:24:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.1.2) lib/rack/sendfile.rb:113:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (3.12.2) lib/puma/configuration.rb:227:in `call'
puma (3.12.2) lib/puma/server.rb:674:in `handle_request'
puma (3.12.2) lib/puma/server.rb:476:in `process_client'
puma (3.12.2) lib/puma/server.rb:334:in `block in run'
puma (3.12.2) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
